name: Deploy to Production

on:
  workflow_dispatch: {}

env:
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
  PROJECT_PREFIX: 'multiapp'
  GCR_REPO: gcr.io/${{ secrets.GCP_PROJECT_ID }}

jobs:
  pull-and-deploy:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'Authenticate gcloud'
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          create_credentials_file: true

      - name: 'Set up gcloud'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Docker Login'
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Add COMMIT_SHA env
        run: |
          echo "COMMIT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Verify Images Exist
        run: |
          docker pull $GCR_REPO/$PROJECT_PREFIX-frontend:$COMMIT_SHA

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init and Apply
        run: |
          cd deploy
          echo '${{ secrets.GCP_SA_KEY }}' > ./gcp-key-file.json
          export GOOGLE_APPLICATION_CREDENTIALS=./gcp-key-file.json
          export TF_VAR_frontend_image_tag=$COMMIT_SHA
          terraform init
          terraform workspace select prod || terraform workspace new prod
          terraform apply -auto-approve
          cd ..

      - name: Tag Production Images
        run: |
          docker tag $GCR_REPO/$PROJECT_PREFIX-frontend:$COMMIT_SHA $GCR_REPO/$PROJECT_PREFIX-frontend:prod
          docker push $GCR_REPO/$PROJECT_PREFIX-frontend:prod
