name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  setup-gcloud:
    name: 'Setup gcloud'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          create_credentials_file: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Prepare Service Account Key
        run: cp "${{ steps.auth.outputs.credentials_file_path }}" ./deploy/gcp-key-file.json

      - name: 'Test gcloud'
        run: 'gcloud info'

      - name: Upload service account key
        uses: actions/upload-artifact@v2
        with:
          name: service-account-key
          path: ./deploy/gcp-key-file.json

  deploy-to-staging:
    name: 'Deploy to Staging'
    runs-on: ubuntu-latest
    needs: setup-gcloud
    if: github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download service account key
        uses: actions/download-artifact@v2
        with:
          name: service-account-key
          path: ./deploy

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Debug log
        run: |
          echo "google_application_credentials ===> $GOOGLE_APPLICATION_CREDENTIALS"

      - name: Terraform Init and Apply
        run: |
          cd deploy
          ls -la
          export GOOGLE_APPLICATION_CREDENTIALS=./gcp-key-file.json
          echo "Automatic deployment to STAGING"
          terraform init
          terraform workspace select test
          terraform apply -auto-approve
          cd ..

  deploy-to-production:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    needs: setup-gcloud
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download service account key
        uses: actions/download-artifact@v2
        with:
          name: service-account-key
          path: ./deploy

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init and Apply
        run: |
          cd deploy
          echo "Manual deployment to PRODUCTION"
          terraform init
          terraform workspace select prod
          terraform apply -auto-approve
          cd ..
