name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  setup-gcloud:
    name: 'Setup gcloud'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          create_credentials_file: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Test gcloud'
        run: 'gcloud info'

  deploy-to-staging:
    name: 'Deploy to Staging'
    runs-on: ubuntu-latest
    needs: setup-gcloud
    if: github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Prepare Service Account Key
        run: cp "${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" ./deploy/gcp-key-file.json

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init and Apply
        run: |
          cd deploy
          echo "Automatic deployment to STAGING"
          terraform init
          terraform workspace select test
          terraform apply -auto-approve
          cd ..

  deploy-to-production:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    needs: setup-gcloud
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Prepare Service Account Key
        run: cp "${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" ./deploy/gcp-key-file.json

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init and Apply
        run: |
          cd deploy
          echo "Manual deployment to PRODUCTION"
          terraform init
          terraform workspace select prod
          terraform apply -auto-approve
          cd ..
