name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  setup-gcloud:
    name: 'Setup gcloud'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Test gcloud'
        run: 'gcloud info'

  deploy-to-staging:
    name: 'Deploy to Staging'
    runs-on: ubuntu-latest
    needs: setup-gcloud

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init and Apply
        run: |
          cd deploy
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Automatic deployment to staging environment"
            terraform workspace select test
            terraform init
            terraform apply -auto-approve
            cd ..
          fi

  deploy-to-production:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    needs: setup-gcloud
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init and Apply
        run: |
          cd deploy
          echo "Manual deployment to production environment"
          terraform workspace select prod
          terraform init
          terraform apply -auto-approve
          cd ..
